## Bag Of Words

In [1]:
x= ['which book is this','this is book and this is math']

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
countvectorizer = CountVectorizer()
count = countvectorizer.fit_transform(x)

In [5]:
count.toarray()

array([[0, 1, 1, 0, 1, 1],
       [1, 1, 2, 1, 2, 0]], dtype=int64)

In [6]:
countvectorizer.get_feature_names()

['and', 'book', 'is', 'math', 'this', 'which']

In [30]:
import pandas as pd
import numpy as np

In [9]:
bow=pd.DataFrame(count.toarray(),columns=countvectorizer.get_feature_names())
bow

and  book  is  math  this  which
0    0     1   1     0     1      1
1    1     1   2     1     2      0

## Term Frequency

In [10]:
tf = bow.copy()

In [12]:
for index, row in enumerate(tf.iterrows()):
    for col in row[1].index:
        tf.loc[index,col]=tf.loc[index,col]/sum(row[1].values)

In [13]:
tf

and      book        is      math      this  which
0  0.000000  0.250000  0.250000  0.000000  0.250000   0.25
1  0.142857  0.142857  0.285714  0.142857  0.285714   0.00

## Inverse Document Frequency | IDF
### IDF = log((N+1)/(n+1)) +1
### N is total number of rows and n is total occuracnce

In [ ]:
bb = bow.astype('bool')

In [18]:
bb

and  book    is   math  this  which
0  False  True  True  False  True   True
1   True  True  True   True  True  False

In [20]:
bb['is'].sum()

2

In [21]:
bb.columns

Index(['and', 'book', 'is', 'math', 'this', 'which'], dtype='object')

In [19]:
nz = []

In [22]:
for col in bb.columns:
    nz.append(bb[col].sum())

In [23]:
nz

[1, 2, 2, 1, 2, 1]

In [24]:
idf =[]

In [27]:
N=bb.shape[0]

In [31]:
for index, col in enumerate(bb.columns):
    idf.append(np.log((N+1)/(nz[index]+1))+1)

In [32]:
idf

[1.4054651081081644, 1.0, 1.0, 1.4054651081081644, 1.0, 1.4054651081081644]

### TFIDF TF*IDF

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
x

['which book is this', 'this is book and this is math']

In [35]:
tfidf = TfidfVectorizer()

In [36]:
X = tfidf.fit_transform(x)

In [42]:
print(X.toarray())

[[0.         0.44832087 0.44832087 0.         0.44832087 0.63009934]
 [0.39054766 0.27787788 0.55575576 0.39054766 0.55575576 0.        ]]


In [41]:
print(tfidf.idf_)

[1.40546511 1.         1.         1.40546511 1.         1.40546511]
